# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hubblesindia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire', '~> 4.8'
pod 'AlamofireImage'
  # Pods for Hubblesindia

  target 'HubblesindiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HubblesindiaUITests' do
    # Pods for testing
  end

end
